#!/usr/bin/env bash

command -v git &>/dev/null || (echo 'Install git' ; exit 1)
command -v flock &>/dev/null || (echo 'Install flock' ; exit 1)
command -v gpg &>/dev/null || (echo 'Install gpg' ; exit 1)

code_dir="${BASH_SOURCE%/*}"
. "${code_dir}/source_me.bash" || (echo 'Missing source_me.bash' ; exit 1)
rm -rf "${GIBBERISH_DIR}"

echo 'You already have a repository in cloud, right?
If not, create one at any of the following for free:
github.com, gitlab.com, sourceforge.net, bitbucket.org
'
read -ep 'URL: ' url
[[ -z "${url}" ]] && exit
uri="${url#*:\/\/}"
protocol="${url%:\/\/*}"

if [[ "${protocol}" == "file" ]] || [[ -n "${protocol}" ]]; then
  fetch_url="${uri}"
  push_url="${uri}"
  localhost="true"
else
  fetch_url="git://${uri}"
  localhost="false"
fi

if [[ "${protocol}" == "ssh" ]]; then
  echo 'No support for ssh yet. Lets use https.'
  protocol="https"
fi

if [[ "${protocol}" == "https" ]]; then
  read -ep 'Username: ' uid
  read -ep 'Passwd/PAT: ' pass
  tput cuu1; tput el1; echo 'Got your passwd.'
  push_url="https://${uid}:${pass}@${uri}"
fi

echo 'You shall be using this PC as'
while read -p '1. Server 2. Client: ' -n1 choice ; do
  case "${choice}" in
    1)config="server"; talkto="client"; break;;
    2)config="client"; talkto="server"; break;;
    *)echo 'Tip: Type either 1 or 2';;
  esac
done
echo

if ! "${localhost}"; then
  echo 'Make sure you are connected to internet. Press any key after that.'
  read -sn1
fi

echo "Configuring ${config}..."
GIBBERISH_filesys

git clone "${fetch_url}" "${incoming_dir}" || (echo exiting; exit 1)

ln "${code_dir}/post-commit" "${incoming_dir}/.git/hooks/post-commit" || \
  (echo 'Missing post-commit hook' ; exit 1)

cd "${incoming_dir}"
git remote set-url --push origin "${push_url}"

# Check if repo has atleast one commit; create a commit if there is none
git switch --quiet "${config}" &>/dev/null || \
(git checkout --quiet -b "${config}"
git commit --allow-empty -m 'Root commit'; git push --quiet origin "${config}")

until git tag last_read &>/dev/null; do git tag -d last_read; done

# Create outgoing directory; checked out with appropriate branch
git worktree add "${outgoing_dir}" "${talkto}" &>/dev/null || \
(git worktree add --quiet -b "${talkto}" "${outgoing_dir}"
git push --quiet origin "${talkto}")
