#!/usr/bin/env bash
# Source the file 'source_me.bash' before executing this file

command -v git || (echo 'Install git' ; exit) 
GBRS_filesys || (echo "Source 'source_me.bash' and relaunch"; exit)

echo 'You already have a repository in cloud, right?
If not, create one at any of the following for free:
github.com, gitlab.com, sourceforge.net, bitbucket.org
'
read -ep 'URL: ' url
[[ -z "${url}" ]] && exit
uri="${url#*:\/\/}"
fetch_url="git://${uri}"
protocol="${url%:\/\/*}"
[[ "${protocol}"=="ssh" ]] && echo 'No support for ssh yet. Lets use https.'

read -ep 'Username: ' uid
read -ep 'Passwd/PAT: ' pass
tput cuu1; tput el1; echo 'Got your passwd.'

push_url="https://${uid}:${pass}@${uri}"

echo 'You shall be using this PC as'
read -p '1. Server 2. Client: ' -n1 choice
while true;do
  case "${choice}" in
    1)config="server"; talkto="client"; break;;
    2)config="client"; talkto="server"; break;;
    *)read -p 'Type either 1 or 2: ' -n1 choice;;
  esac
done

echo 'Make sure you are connected to internet. Press any key after that.'
read -sn1

echo "Configuring ${config}..."

mkdir -p "${GBRS_DIR}"
touch "${interface}"

(
set -o errexit
git clone --verbose --bare "${fetch_url}" "${GIT_DIR}"
git remote set-url --push origin "${push_url}"
git worktree add --track -b "${config}" "${incoming_dir}" "origin/${config}"
git worktree add --track -b "${talkto}" "${outgoing_dir}" "origin/${talkto}"
)
