#!/usr/bin/env bash

push(){
  cd "${outgoing_dir}"
  until git push --quiet --no-verify origin "${push_branch}"; do
    git pull --rebase --quiet --no-verify origin "${push_branch}"
  done
}

flock -x "${push_lock}" push &
